title: astro-pi-flight-case-mk2
hero_image: images/banner.png
description: astro-pi-flight-case-mk2 description
version: 4
listed: false
copyedit: false
last_tested: "2021-08-27"
steps:
- title: Introduction
- title: Get the 3D files
- title: Print each part
- title: Remove the scaffolding
- title: Install the camera
- title: Install the Raspberry Pi
- title: Soldering and installing the push-buttons
- title: Install the PIR sensor
- title: Connect internal wiring to the Raspberry Pi
- title: Assemble the case
- title: Test the hardware
- title: "Challenge: improve your case"