title: 3D-Printed Astro Pi Mark II flight case
hero_image: images/banner.png
description: Use a 3D printer to create a replica Astro Pi Mark II Flight Case like the ones sent to the ISS in 2021
version: 4
listed: false
copyedit: false
last_tested: "2021-08-27"
steps:
- title: Introduction
- title: Get the 3D files
- title: Print each part
- title: Remove the scaffolding
- title: Install the camera
- title: Install the Raspberry Pi
- title: Solder and install the push-buttons
- title: Install the PIR sensor
- title: Connect internal wiring to the Raspberry Pi
- title: Assemble the case
- title: Test the hardware
- title: Challenge: Improve your case
